alias repos="cd ~/source/repos"
alias local="cd ~/source/local"
alias laragon="cd c:/laragon/www"

alias add="git add"
alias all="git add ."
alias branch="git branch"
alias commit="git commit -m"
alias check="git checkout"
alias dev="git checkout dev"
alias fetch="git fetch"
alias merge="git merge"
alias push="git push"
alias upstream="git push --set-upstream origin"
alias pull="git pull"
alias status="git status"
alias cleangit="git remote update origin --prune"

alias ngs="ng serve"
